apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hlttln7d4-nodejs 
  janus-idp.io/tekton: hlttln7d4-nodejs
  backstage.io/kubernetes-id: hlttln7d4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hlttln7d4-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  